title: Testing GitHub Pages
author: Mirthe Valentijn

navbar-links:
  About Me: "aboutme"
  Docs: "Docs"
  Author's home: "https://mirthe.org"

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
